#!/bin/sh
#
# Author:  Praveen Kumar Gunasekar
# Email:   praveen.gunasekar@happiestminds.com
# Date:    September 2016
# Purpose: Icinga-check for monitoring icinga service

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1.00 $' | sed -e 's/[^0-9.]//g'`
iscsi_target='iqn.2006-01.com.openfiler:tsn.3af9bd6b7b5b'
. $PROGPATH/utils.sh

INFLUX_CHECK=`/etc/init.d/influxdb status|tr '[A-Z]' '[a-z]'| sed "/^\s*$/d"`
CHROF_CHECK=`/etc/init.d/chronograf status|tr '[A-Z]' '[a-z]'`
ISCSI_AVAIL=`iscsiadm -m session | grep $iscsi_target | wc -l`
MYSQL_MNT=`mount | grep -w '/content' | wc -l`
ISCSI_MNT=`mount | grep -w '/iscsi_mount' | wc -l`
mysql_size=`du /content | awk '{print $1}'`
iscsi_size=`du /iscsi_mount | awk '{print $1}'`

# Checking the influxdb is up and running
case "$INFLUX_CHECK" in
        *"not running"*)
              ISERVICE="\nWARNING: $INFLUX_CHECK"
              INSTATE=$STATE_WARNING
        ;;
        *"running"*)
              ISERVICE="\nOK: $INFLUX_CHECK"
              INSTATE=$STATE_OK
        ;;
        *)
              ISERVICE="\nCRITICAL: InfluxDB is not running"
              INSTATE=$STATE_CRITICAL
        ;;
esac

# Checking the Chronograf is up and running
case "$CHROF_CHECK" in
        *"not running"*)
              CSERVICE="WARNING: $CHROF_CHECK"
              CSTATE=$STATE_WARNING
        ;;
        *"running"*)
              CSERVICE="OK: $CHROF_CHECK"
              CSTATE=$STATE_OK
        ;;
        *)
              CSERVICE="CRITICAL: Chronograf is not installed"
              CSTATE=$STATE_CRITICAL
        ;;
esac

# Checking for ISCSI status 
if [ "$ISCSI_AVAIL" -eq 1 ]; then
	ISCSI_STAT="OK: ISCSI has been mounted successfully"
	ISCSISTATE=$STATE_OK
else
	ISCSI_STAT="WARNING: ISCSI not mounted"
	ISCSISTATE=$STATE_WARNING
fi

# Checking whether the mount points are available.
MOUNT_STATUS=''

if [ $MYSQL_MNT -eq 0 ] || [ $ISCSI_MNT -eq 0 ]; then
    MOUNT_STATUS="WARNING: MYSQL partition or ISCSI partition not available"
    MOUNTSTATE=$STATE_WARNING
elif [ $MYSQL_MNT ] && [ $ISCSI_MNT ]; then
    MOUNT_STATUS="OK: MYSQL and ISCSI partitions are available"
    MOUNTSTATE=$STATE_OK
else
    MOUNT_STATUS="UNKNOWN: MYSQL partition or ISCSI partition not available"
    MOUNTSTATE=$STATE_UNKNOWN
fi

# Checking for the size of both the partition
if [ "$mysql_size" != "$iscsi_size" ]; then
    SIZE_STATUS="WARNING: MYSQL not sysnced with ISCSI; Please run rsync"
    SIZESTAT=$STATE_WARNING
else
    SIZE_STATUS='OK: MYSQL, ISCSI are in SYNCHRONIZED'
    SIZESTAT=$STATE_OK
fi


#echo -e "\n$ISERVICE$CSERVICE\n$ISCSI_STAT\n$MOUNT_STATUS\n$SIZE_STATUS" | grep -v "^$"
echo -e "$ISERVICE\n$CSERVICE\n$ISCSI_STAT\n$MOUNT_STATUS\n$SIZE_STATUS" | sed '/^\s*$/d'

if [ $INSTATE -lt 0 -o $INSTATE -gt 3 -o $CSTATE -lt 0 -o $CSTATE -gt 3 -o $ISCSISTATE -lt 0 -o $ISCSISTATE -gt 3 -o $MOUNTSTATE -lt 0 -o $MOUNTSTATE -gt 3 -o $SIZESTAT -lt 0 -o $SIZESTAT -gt 3 ]; then
        STATE=$STATE_UNKNOWN
elif [ $INSTATE -eq 0 -a $CSTATE -eq 0 -a $ISCSISTATE -eq 0 -a $MOUNTSTATE -eq 0 -a $SIZESTAT -eq 0 ]; then
        STATE=$STATE_OK
elif [ $INSTATE -eq 1 -o $CSTATE -eq 1 -o $ISCSISTATE -eq 1 -o $MOUNTSTATE -eq 1 -o $SIZESTAT -eq 1 ]; then
        STATE=$STATE_WARNING
elif [ $INSTATE -eq 2 -o $CSTATE -eq 2 -o $ISCSISTATE -eq 2 -o $MOUNTSTATE -eq 2 -o $SIZESTAT -eq 2 ]; then
        STATE=$STATE_CRITICAL
elif [ $INSTATE -eq 3 -o $CSTATE -eq 3 -o $ISCSISTATE -eq 3 -o $MOUNTSTATE -eq 3 -o $SIZESTAT -eq 3 ]; then
        STATE=$STATE_UNKNOWN
else
        STATE=$STATE_UNKNOWN
fi
exit $STATE

