#!/bin/sh
#
# Author:  Praveen Kumar Gunasekar
# Email:   praveen.gunasekar@happiestminds.com
# Date:    September 2016
# Purpose: Monitoring the Iscsi target and mount points

PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1.00 $' | sed -e 's/[^0-9.]//g'`
iscsi_target='iqn.2006-01.com.openfiler:tsn.3af9bd6b7b5b'
. $PROGPATH/utils.sh

ISCSI_AVAIL=`iscsiadm -m session | grep $iscsi_target | wc -l`
MYSQL_MNT=`mount | grep -w '/content' | wc -l`
ISCSI_MNT=`mount | grep -w '/iscsi_mount' | wc -l`


# Checking for ISCSI status
if [ "$ISCSI_AVAIL" -eq 1 ]; then
        ISCSI_STAT="OK: ISCSI has been mounted successfully"
        ISCSISTATE=$STATE_OK
else
        ISCSI_STAT="WARNING: ISCSI not mounted"
        ISCSISTATE=$STATE_WARNING
fi

# Checking whether the mount points are available.
MOUNT_STATUS=''

if [ $MYSQL_MNT -eq 0 ] || [ $ISCSI_MNT -eq 0 ]; then
    MOUNT_STATUS="WARNING: MYSQL partition or ISCSI partition not available"
    MOUNTSTATE=$STATE_WARNING
elif [ $MYSQL_MNT ] && [ $ISCSI_MNT ]; then
    MOUNT_STATUS="OK: MYSQL and ISCSI partitions are available"
    MOUNTSTATE=$STATE_OK
else
    MOUNT_STATUS="UNKNOWN: MYSQL partition or ISCSI partition not available"
    MOUNTSTATE=$STATE_UNKNOWN
fi

#echo -e "\n$ISERVICE$CSERVICE\n$ISCSI_STAT\n$MOUNT_STATUS\n$SIZE_STATUS" | grep -v "^$"
echo -e "$ISCSI_STAT\n$MOUNT_STATUS" | sed '/^\s*$/d'

if [ $ISCSISTATE -lt 0 -o $ISCSISTATE -gt 3 -o $MOUNTSTATE -lt 0 -o $MOUNTSTATE -gt 3 ]; then
        STATE=$STATE_UNKNOWN
elif [ $ISCSISTATE -eq 0 -a $MOUNTSTATE -eq 0 ]; then
        STATE=$STATE_OK
elif [ $ISCSISTATE -eq 1 -o $MOUNTSTATE -eq 1 ]; then
        STATE=$STATE_WARNING
elif [ $ISCSISTATE -eq 2 -o $MOUNTSTATE -eq 2 ]; then
        STATE=$STATE_CRITICAL
elif [ $CSTATE -eq 3 -o $ISCSISTATE -eq 3 -o $MOUNTSTATE -eq 3 ]; then
        STATE=$STATE_UNKNOWN
else
        STATE=$STATE_UNKNOWN
fi
exit $STATE

