#!/bin/bash
#
# Author:  Praveen Kumar Gunasekar
# Email:   praveen.gunasekar@happiestminds.com
# Date:    September 2016
# Purpose: Monitoring the Iscsi target and mount points


PROGNAME=`basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1.00 $' | sed -e 's/[^0-9.]//g'`
. $PROGPATH/utils.sh

in_user_name="icingauser"
in_pwd="icinga@123"
in_db="arista_disks"
mysql_mnt="/content"
iscsi_mnt="/iscsi_mount"
sub=''
reci='test1@arista.com,test2@arista.com'

mysql_size=`influx -username=$in_user_name -password=$in_pwd -execute="select * from drive_info" -database=$in_db -format=column | grep $mysql_mnt | awk '{print $NF}'| tail -n 1`

iscsi_size=`influx -username=$in_user_name -password=$in_pwd -execute="select * from drive_info" -database=$in_db -format=column | grep $iscsi_mnt | awk '{print $NF}'| tail -n 1`

# Checking for the size of both the partition
if [ "$mysql_size" != "$iscsi_size" ]; then
    SIZE_STATUS="WARNING: MYSQL not sysnced with ISCSI; Please run rsync"
    SIZESTAT=$STATE_WARNING
    sub='ICINGA2: RSYNC issue'
    echo 'MYSQL partition and ISCSI partition are not synced.. Please check the rsync......' | mail -s $sub $reci -aFrom:Alerts@arista.com
else
    SIZE_STATUS='OK: MYSQL, ISCSI are in SYNCHRONIZED'
    SIZESTAT=$STATE_OK
fi

echo -e "MYSQL_SIZE=$mysql_size\nISCSI_SIZE=$iscsi_size\n$SIZE_STATUS" | sed '/^\s*$/d'

if [ $SIZESTAT -lt 0 -o $SIZESTAT -gt 3 ]; then
        STATE=$STATE_UNKNOWN
elif [ $SIZESTAT -eq 0 ]; then
        STATE=$STATE_OK
elif [ $SIZESTAT -eq 1 ]; then
        STATE=$STATE_WARNING
elif [ $SIZESTAT -eq 2 ]; then
        STATE=$STATE_CRITICAL
elif [ $SIZESTAT -eq 3 ]; then
        STATE=$STATE_UNKNOWN
else
        STATE=$STATE_UNKNOWN
fi
exit $STATE



